version: "2.27.0"

services:
  postgres:
    container_name: data_collector_postgres
    image: postgres:12.19-bullseye
    env_file:
      - .env/postgres.env
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./SqlScripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: data_collector_pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env/pgadmin.env
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    ports:
      - "9999:80"
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
