name: "Run tests"

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract secret files
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          bash decrypt.sh $GPG_PASSPHRASE

      - name: Run tests
        run: |
          mkdir .vs
          docker compose -f docker-compose.test.yml run test
